# Functions

Functions allow you to create reusable blocks of code that perform specific tasks. They are essential for writing organized, efficient, and maintainable code in Python. Functions allow you to break down complex tasks into smaller, manageable parts, making your code easier to understand, maintain and saving you from duplicating code.

To define a function in Python, use the `def` keyword. Like this:

In [ ]:
def say_hello():
    print('Hello!')

You can then call the function like this.

In [ ]:
say_hello()

Hello!


Like you might expect, functions can take arguments, e.g.:

In [ ]:
def say_hello(name):
    print('Hello,', name)
    
say_hello('Bob')

Hello, Bob


In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


A function can return just anything, for example the first element of the input:

In [ ]:
def get_first_element(collection):
    return collection[0]

This function now works with lists, tuples and strings (in fact any indexable collection).

In [ ]:
get_first_element([5, 6, 7])

5

In [ ]:
get_first_element((6, 7, 8))

6

In [ ]:
get_first_element('abc')

'a'

<div class='alert alert-warning'>

<h4>Ex1.8. Write a function which takes a list (or other iterable, like a string) as input, and tell whether it containts any duplicates (the same number more than once). </h4>
</div>   

In [ ]:
# Ex8


In [ ]:
# here you can test if it works

test1 = 'abd43ghj'
test2 = 'abcefg'

duplicates(test1)

No duplicates


## Rules for calling (applying) functions in python:

you can choose to feed in arguments either by name of the argument, or pass them in the right order. 

In [ ]:
def get_an_element(collection, index):
    return collection[index]

get_an_element('abcdef', 4)

'e'

In [ ]:
# by order
get_an_element('abcdef', 4)

'e'

In [ ]:
# by name:
get_an_element(collection='abcdef', index=4)

'e'

When you call by name, the order can be arbitrary:

In [ ]:
get_an_element(index=4, collection='abcdef')

'e'

We refer to these as keyword-arguments when we use the name. A rule states you cannot pass in a keyword-argument before a positional argument, so the following won't work:

In [ ]:
get_an_element(collection='abcdef', 4)

SyntaxError: positional argument follows keyword argument (<ipython-input-47-420d5bf658cd>, line 1)

But this will:

In [ ]:
get_an_element('abcdef', index=4)

'e'

## Default arguments

When we construct a function, we can pass in a default value in the `def` statement. If we don't pass in that argument when calling the function, it will just use the default value:

In [ ]:
def get_an_element(collection, index=0):
    return collection[index]

get_an_element('abcdef')

'a'

But we have the power to change that at any point:

In [ ]:
get_an_element('abcdef', 4)

'e'

In other words, these arguments are *optional*

In [ ]:
get_an_element('abcdef')                        # OK, index has its default value
get_an_element('abcdef', index=4)               # OK, override default value of index
get_an_element('abcdef', 4)                     # Works, not considered normal
get_an_element(collection='abcdef', index=4)    # Works, not considered normal
# get_an_element(collection='abcdef', 4)          # Illegal
# get_an_element(index=4, 'abcdef')               # Illegal, but also ambiguous

'e'

You can also write functions that take an arbitrary number of arguments. Here, the asterisk `*` is called the "splat" operator.

In [ ]:
def print_all_args(*args):
    print(args)

print_all_args('a', 'b', 'c')

('a', 'b', 'c')


Note that `args` becomes a tuple containing all the arguments. You can also collect keyword arguments into a dictionary with the double-splat operator.

In [ ]:
def print_all_args(*args, **kwargs):
    print(args, kwargs)
    
print_all_args('a', 'b', 'c', name='Arvid', place='Seili')

('a', 'b', 'c') {'name': 'Arvid', 'place': 'Seili'}


A combination of actual arguments and splats also work "as expected", although it's not always obvious what is expected. :-)

In [ ]:
def print_all_args(a, b, *args, c=1, **kwargs):
    print(a, b, c, args, kwargs)
    
print_all_args(1, 2, 3, 4, 5, c=6, d=7, e=8)

1 2 6 (3, 4, 5) {'d': 7, 'e': 8}


Splatting also works the other way, for example, here's a function that sums three numbers:

In [ ]:
def sum_three(a, b, c):
    return a + b + c

We can call it like this:

In [ ]:
args = [5, 6, 7]
sum_three(args[0], args[1], args[2])

18

But this is much more elegant:

In [ ]:
sum_three(*args)

18

You can mix splats and normal arguments.

In [ ]:
sum_three(5, *[6, 7])

18

In [ ]:
sum_three(*[5], 6, *[7])

18

A similar construction exists for keyword arguments, which requires a dictionary.

In [ ]:
kwargs = {'a': 5, 'b': 6, 'c': 7}
sum_three(**kwargs)

18

<div class='alert alert-warning'>

<h4> Exercise 9: can you make a function `mult` that will return the product of any number of inputs?
NB: python has a builtin function `sum` that does it for sums </h4>
</div>  

In [ ]:
# Ex9


Combinations of regular arguments, named arguments, splat arguments and double-splat keyword arguments all work, and should produce the expected results. If Python ever produces an error, you are probably just trying to do something that doesn't make sense.

# Python libraries

By default Python has many available functions and classes. Some of these functions are only accessible through importing specialized modules. **Library** is an umbrella term referring to reusable chunk of code. Let's say you wish to do math operations. We use the `import` to make the math functions available: 


In [ ]:
import math

Now we can access `math` library functionalities by calling `math.` followed by the function. For instance, Euler's number is:

In [ ]:
math.e

2.718281828459045

In [ ]:
math.sin(1)

0.8414709848078965

But more vast is the `numpy` library, which crucially let's you work with matrices and vectors. We usually import it using an alias `np`. (More about useful libraries in next notebooks)

In [2]:
import numpy as np

In [ ]:
np.e

2.718281828459045

In [3]:
mat = np.array([[0,1,2],[3,4,5],[6,7,8]]) #making a matrix/2D array
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Finding right library and function

If you're wondering how to find the right library for your task and, once found, how to locate the specific functions you need, don't worry. The next section will guide you through this process step by step.

**Define Your Task** : Clearly defining what you want to achieve. Whether it's data analysis, web development, machine learning, or any other task.

**Search and Explore** : Once you've defined your task, start your search. Google is always your friend.

**Check Documentation** : It provides valuable information on what the library does, how to install it, and how to use it(functions)

*For an example, how to get the transpose of "mat" 2D array/matrix you have created earlier.*
<p>
mat = [[0, 1, 2],
            [3, 4, 5],
            [6, 7, 8]]
<p>
The transpose of a matrix involves swapping its rows and columns. 
<p>
mat_T =  [0, 3, 6],
               [1, 4, 7],
               [2, 5, 8]
<p>
Start by searching/googling for a Python library that's well-suited for matrix operations and transposition. Most likely, you'll come across NumPy as the top suggested library. Then refer the <a href = "https://numpy.org/doc/stable/" >NumPy documentation</a> , type in the specific functions you need for this task, such as 'array creation' or 'transpose.' This will direct you to the relevant support pages. From the support pages, you can read and learn how to use these functions effectively.

<p>

</div>  

In [5]:
np.transpose(mat)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

or

In [6]:
mat.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=174a646e-27d4-4666-a2b4-2d7bb1c47bf5' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>